[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I", "B", "UP"]
ignore = ["E203", "E501"]

[tool.ruff.isort]
known-first-party = ["app", "modules", "core"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["services/api", "packages"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = false
